Fix copy of null MS
casacore/casacore pull request #1138
Opened 2021-11-25 11:08 UTC by gervandiepen

The MS copy constructor and assignment now test for a null MS object.

Close #1135

2021-11-29 09:49 UTC, mnijhuis-tos requested changes

2021-11-29 09:49 UTC, mnijhuis-tos commented on ms/MeasurementSets/MeasurementSet.cc
>      if (!hasBeenDestroyed_p  &&  !validate()) {
Optional: You could combine the two if statements into one statement.

2021-11-29 09:49 UTC, mnijhuis-tos commented on ms/MeasurementSets/MeasurementSet.cc
>    hasBeenDestroyed_p(False)
The default constructor, which yields a Null MS, initializes `hasBeenDestroyed_p` to True. Can you initialize `hasBeenDestroyed_p` to `other.isNull()` here? Then you also don't need to modify the destructor.

2021-11-29 09:49 UTC, mnijhuis-tos commented on ms/MeasurementSets/MeasurementSet.cc
> +        if (! (isNull()  ||  other.isNull())) {
Why do you need the `isNull()` check? It looks like checking `if (!other.isNull())` should be enough here.

2021-11-29 09:49 UTC, mnijhuis-tos commented on ms/MeasurementSets/MeasurementSet.cc
> +        }
GitHub shows different indentation levels in this function, which is confusing.

2021-11-29 13:34 UTC, mnijhuis-tos requested changes

2021-11-29 13:34 UTC, mnijhuis-tos commented on ms/MeasurementSets/MeasurementSet.cc
>    hasBeenDestroyed_p(False)
I see you now set `hasBeenDestroyed_p` to `other.hasBeenDestroyed_p` if `other` is not null. I think you can directly initialize `hasBeenDestroyed_p` to `other.hasBeenDestroyed_p` here instead, which is a littile simpler.

2021-11-29 14:56 UTC, gervandiepen commented
I think it's better to assign hasBeenDestroyed_p later because an exception might be thrown in the constructor in which case the destructor should not destroy too much.

2021-11-29 15:52 UTC, mnijhuis-tos commented
> I think it's better to assign hasBeenDestroyed_p later because an exception might be thrown in the constructor in which case the destructor should not destroy too much.

If an exception occurs in the constructor, the destructor is never called, since destructors are only called for completely initialized objects.

2021-12-01 12:08 UTC, mnijhuis-tos approved these changes

2021-12-02 17:15 UTC, merged