CAS 13973 add methods to retrieve alma specific spw data
casacore/casacore pull request #1290
Opened 2023-02-15 00:46 UTC by dmehring

2023-02-15 08:49 UTC, dpetry requested changes
Would be good to add a few lines of comments explaining where the ASDM_RECEIVER table and the concept of SPW subwindows comes from since both of these are not part of the standard MS.
Concerning testing: how does this code behave when operating on an MS which does not have the ASDM_RECEIVER table, e.g. simulated ALMA data or data from other observatories?

2023-02-15 08:49 UTC, dpetry commented on ms/MSOper/MSMetaData.cc
> +    // for ALMA specific receiver band (RB) info
Maybe add a few more lines of comments on how the the receiver bands are expected to be defined in the ASDM_RECEIVER table and where this table comes from (i.e. that we are expecting importasdm to have copied it over with the "asis" feature verbatim from the ASDM). After all, ASDM_RECEIVER is not a standard MS subtable.

2023-02-15 08:49 UTC, dpetry commented on ms/MSOper/MSMetaData.cc
> +    std::set<uInt> avgSpw, tdmSpw, fdmSpw, wvrSpw, sqldSpw;
Please document somewhere the concept of SPW subwindows. This is not a standard MS feature.

2023-02-15 10:38 UTC, renaudmiel commented
I fully agree with @dpetry 's comments

2023-02-17 00:50 UTC, dmehring commented
I've added requested documentation. The code behaves as it did previously if the ASDM_RECEIVER table doesn't exist; the relevant block of code is only executed if this table exists. See line 4978

2023-02-20 10:35 UTC, dpetry approved these changes

2023-02-20 10:36 UTC, merged